import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '../../components/ui/card';
const ConfirmationForm = ({ email, error, success, confirmationCode, isLoading, handleCodeChange, handleConfirmSignUp, handleResendCode }) => {
    return (_jsxs("div", { className: "flex items-center justify-center min-h-screen bg-gray-100", children: [_jsx("div", { className: 'flex-1', children: "Hi" }), _jsx("div", { className: 'flex-1', children: _jsxs(Card, { className: "w-full max-w-md text-gray-800", children: [_jsxs(CardHeader, { children: [_jsx(CardTitle, { children: "Confirm Your Email" }), _jsxs(CardDescription, { className: 'text-gray-600', children: ["We've sent a confirmation code to ", _jsx("strong", { children: email }), ". Please enter the code below to complete your registration."] })] }), _jsxs(CardContent, { children: [error && (_jsx("div", { className: "mb-4 text-red-500 bg-red-100 p-3 rounded", children: error })), success && (_jsx("div", { className: "mb-4 text-green-500 bg-green-100 p-3 rounded", children: success })), _jsx("form", { onSubmit: handleConfirmSignUp, children: _jsxs("div", { className: "space-y-4", children: [_jsx(Input, { type: "text", className: "text-center", value: confirmationCode, onChange: handleCodeChange, placeholder: "Enter 6-digit code", maxLength: 6, disabled: isLoading, required: true, style: { letterSpacing: '0.5em', fontSize: '1.2em' } }), _jsx(Button, { type: "submit", className: "w-full", disabled: isLoading, children: isLoading ? 'Confirming...' : 'Confirm Email' })] }) })] }), _jsxs(CardFooter, { className: "flex flex-col items-center space-y-2", children: [_jsx(Button, { variant: "link", onClick: handleResendCode, disabled: isLoading, children: "Didn't receive the code? Resend" }), _jsx(Link, { to: "/adminpanel/login", className: "text-sm text-gray-600 hover:underline", children: "Back to Login" })] })] }) })] }));
};
export default ConfirmationForm;
