import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const Scoreboard = ({ scoreboardData, awayTeamName, homeTeamName, awayTeamLogo, homeTeamLogo, }) => {
    if (!scoreboardData) {
        return null;
    }
    const { away_score, home_score, quarter, clock, away_fouls, home_fouls, home_team_offense, } = scoreboardData;
    const isHomeTeamOffense = home_team_offense === '1';
    const TeamLogo = ({ logo, name }) => (logo ? _jsx("img", { src: logo, alt: `${name} Logo`, className: "h-14 w-14 object-contain" }) : _jsx("div", { className: "h-14 w-14 bg-gray-700 rounded-full flex items-center justify-center text-white font-bold text-xl", children: name.substring(0, 3).toUpperCase() }));
    return (_jsxs("div", { className: "w-full max-w-5xl mx-auto font-sans bg-gray-900/80 backdrop-blur-sm text-white rounded-2xl shadow-2xl border-2 border-gray-700/50 overflow-hidden", children: [_jsxs("div", { className: "flex items-center justify-between p-3", children: [_jsxs("div", { className: "flex items-center gap-4 flex-1", children: [_jsx(TeamLogo, { logo: awayTeamLogo, name: awayTeamName }), _jsx("span", { className: "text-3xl font-bold tracking-wider", children: awayTeamName.toUpperCase() })] }), _jsx("div", { className: "text-7xl font-mono font-extrabold text-yellow-300 w-32 text-center", children: away_score }), _jsxs("div", { className: "flex flex-col items-center justify-center text-center px-8", children: [_jsx("div", { className: "text-5xl font-mono font-bold text-red-500 tabular-nums", children: clock }), _jsxs("div", { className: "text-2xl font-semibold tracking-widest", children: ["Q", quarter] })] }), _jsx("div", { className: "text-7xl font-mono font-extrabold text-yellow-300 w-32 text-center", children: home_score }), _jsxs("div", { className: "flex items-center gap-4 flex-1 justify-end", children: [_jsx("span", { className: "text-3xl font-bold tracking-wider", children: homeTeamName.toUpperCase() }), _jsx(TeamLogo, { logo: homeTeamLogo, name: homeTeamName })] })] }), _jsxs("div", { className: "bg-black/50 flex justify-between items-center text-lg px-6 py-1", children: [_jsxs("div", { className: "flex items-center gap-6", children: [_jsx("div", { className: `w-4 h-4 rounded-full bg-red-500 transition-opacity duration-300 ${!isHomeTeamOffense ? 'opacity-100 animate-pulse' : 'opacity-0'}` }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "font-semibold text-gray-400", children: "FOULS" }), _jsx("span", { className: "font-mono text-2xl", children: away_fouls })] })] }), _jsxs("div", { className: "flex items-center gap-6", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "font-semibold text-gray-400", children: "FOULS" }), _jsx("span", { className: "font-mono text-2xl", children: home_fouls })] }), _jsx("div", { className: `w-4 h-4 rounded-full bg-red-500 transition-opacity duration-300 ${isHomeTeamOffense ? 'opacity-100 animate-pulse' : 'opacity-0'}` })] })] })] }));
};
export default Scoreboard;
